site_name: TCC Brenda Santos
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  features:
    - navigation.tabs
extra_css:
  - stylesheets/styles.css

dev_addr: "0.0.0.0:3000"
